### ISSUE TITLE
[Meta] Ciphersuite update

### ISSUE THREAD

**Issue by franziskuskiefer** [raphaelrobert/maelstrom#114]
The ciphersuite needs an overhaul

- [ ] add to config
- [x] rely more on hpke
- [ ] remove unnecessary wrapper

**Comment by kkohbrok** [comment]
Would it be useful to do this in conjunction with #94 ?
